package main;

import java.awt.*;
import java.awt.event.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nodonnel
 */
public class CalendarGUI extends javax.swing.JFrame implements ActionListener {
    // Variables declaration - do not modify
    private javax.swing.JPanel GUIPanel;
    private javax.swing.JPanel calendarDisplayPanel;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel oneMonthLabel;
    private javax.swing.JPanel oneMonthPanel;
    private javax.swing.JLabel threeMonthLabel;
    private javax.swing.JPanel threeMonthPanel;
    private javax.swing.JLabel twelveMonthLabel;
    private javax.swing.JPanel twelveMonthPanel;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;


    String[] months = { "January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December" };
    JComboBox cb;
    Object selectedMonth = "";
    int month = 0;
    CalendarPanel cal = new CalendarPanel();


    // End of variables declaration



    /**
     * Creates new form main.CalendarGUI
     */
    public CalendarGUI() {
        initComponents();
//        MultiMonthPanel p3 = new TwelveMonthPanel(2015, 0);
//        for (CalendarPanel cp : p3.month_calendars) {
//            cal.add(cp);
//        }
//        draw(cal);

//        show_month_display(cal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        GUIPanel = new javax.swing.JPanel();
        instructionsLabel = new javax.swing.JLabel();
        monthTextField = new javax.swing.JTextField();
        monthLabel = new javax.swing.JLabel();
        calendarDisplayPanel = new javax.swing.JPanel();
        oneMonthPanel = new javax.swing.JPanel();
        oneMonthLabel = new javax.swing.JLabel();
        threeMonthPanel = new javax.swing.JPanel();
        threeMonthLabel = new javax.swing.JLabel();
        twelveMonthPanel = new javax.swing.JPanel();
        twelveMonthLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        monthComboBox = new javax.swing.JComboBox<>();
        yearLabel = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calendar Generator");

        GUIPanel.setLayout(new java.awt.GridBagLayout());

        instructionsLabel.setText("Enter the desired calendar type, starting month, and year below, then press \"Update\" to generate the new calendar.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        GUIPanel.add(instructionsLabel, gridBagConstraints);


        monthLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        monthLabel.setText("Starting Month: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        GUIPanel.add(monthLabel, gridBagConstraints);

        calendarDisplayPanel.setLayout(new java.awt.CardLayout());
        calendarDisplayPanel.add(cal);

        oneMonthPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        oneMonthPanel.setLayout(new java.awt.GridBagLayout());

        //oneMonthLabel.setText("" );

        oneMonthPanel.add(oneMonthLabel, new java.awt.GridBagConstraints());

        calendarDisplayPanel.add(oneMonthPanel, "1 Month");

        threeMonthPanel.setLayout(new java.awt.GridBagLayout());

        //threeMonthLabel.setText("threeMonth");
        threeMonthPanel.add(threeMonthLabel, new java.awt.GridBagConstraints());

        calendarDisplayPanel.add(threeMonthPanel, "3 Months");

        twelveMonthPanel.setLayout(new java.awt.GridBagLayout());

        //twelveMonthLabel.setText("twelveMonth");
        twelveMonthPanel.add(twelveMonthLabel, new java.awt.GridBagConstraints());
        twelveMonthLabel.getAccessibleContext().setAccessibleName("12 Months");

        calendarDisplayPanel.add(twelveMonthPanel, "12 Months");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        GUIPanel.add(calendarDisplayPanel, gridBagConstraints);

        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(months));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        GUIPanel.add(monthComboBox, gridBagConstraints);

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Month", "3 Months", "12 Months" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        GUIPanel.add(typeComboBox, gridBagConstraints);

        yearLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yearLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearLabel.setText("Year: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        GUIPanel.add(yearLabel, gridBagConstraints);

        yearTextField.setText("2019");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        GUIPanel.add(yearTextField, gridBagConstraints);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });


        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        GUIPanel.add(updateButton, gridBagConstraints);

        typeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        typeLabel.setText("Calendar Type: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        GUIPanel.add(typeLabel, gridBagConstraints);


        // Draw the GUI after all components have been initialized
        // TODO : extract to separate fucntion
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GUIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GUIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>



    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int year = Integer.parseInt(yearTextField.getText());
        int month = monthComboBox.getSelectedIndex();

        MultiMonthPanel month_display = null;

        switch (typeComboBox.getSelectedIndex()){
            case 0 :
                month_display = new MultiMonthPanel(1, year, month);
                break;

            case 1 :
                month_display = new ThreeMonthPanel(year, month);
                break;

            case 2 : {
                month_display = new TwelveMonthPanel(year, month);
                break;
            }
        }

//        cal.add(new CalendarPanel());
//        calendarDisplayPanel.add(cal);
//        CardLayout cl = (CardLayout) (calendarDisplayPanel.getLayout());
//        cl.show(calendarDisplayPanel, typeComboBox.getItemAt(typeComboBox.getSelectedIndex()));
//        calendarDisplayPanel.repaint();
//        calendarDisplayPanel.revalidate();

        JPanel jp = new JPanel();
        for (CalendarPanel cp : month_display.month_calendars) {
            jp.add(cp);
        }

        cal = (CalendarPanel) jp;
        repaint();
    }

    public void actionPerformed(ActionEvent e) {

        // determine action type
        cb = (JComboBox)e.getSource();
        selectedMonth = cb.getSelectedItem();

        CalendarPanel c;

        if(selectedMonth.toString().equals("January")){
            // build main.CalendarPanel
            c = new CalendarPanel(2019, 1);

            // set the panel into the GUI
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalendarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalendarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalendarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalendarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalendarGUI().setVisible(true);
            }
        });
    }


}
